### ISSUE TITLE
khard search does not find anything

### ISSUE THREAD

**Issue by matthiasbeyer** [scheibler/khard#132]
`khard search name` finds nothing but `khard | grep name` finds the name... what's the problem here?

**Comment by scheibler** [comment]
Khard's general syntax is

```
khard [--global_args] [action] {--action_specific_args] [search_terms]
```

You may obtain a list of all available actions with

```
khard --help
```

and the help for a specific action with

```
khard [action] --help
```

The problem is, that your specified action `search` does not exist. Therefore khard uses the default
action from the khard config file. Without changes, that should be the phone action. So the commands

```
khard name
```

and

```
khard phone name
```

should produce the same result and the search should work too.
