### ISSUE TITLE
Handling partial birthdays

### ISSUE THREAD

**Issue by samdmarshall** [scheibler/khard#134]
I have a bunch of contacts that I have birthdays stored for without their birth-year attached in my iCloud account. Apparently the way that Apple handles this is by exporting the VCF as the following:

```
BDAY;X-APPLE-OMIT-YEAR=1604:1604-05-09
```

This works fine in Apple's software, but not so much when attaching this to `khard`, as it will display their birth-year as 1604. I assume that Apple does this as a work-around to the official spec, and that there is no proper way to handle a date without a year attached to it. Is there a way I could work around this to have `khard` only display the available date data?

Thanks.

**Comment by scheibler** [comment]
That depends on the vcard version, you are using. Vcard 4.0 allows dates without a year component.
Try to use the following in khard's contacts editor:

```
Birthday : --mm-dd
```

Unfortunately vcard 3.0 lags that feature. So Apple defined their own private extension.  My
workaround for khard is similar: I defined 1900 as placeholder while Apple selected 1604.  Therefore
in khard you would enter:

```
Birthday : 1900-mm-dd
```

But these two solutions aren't compatible. Worse: If you edit a vcard with Apples private
X-APPLE-OMIT-YEAR, khard will strip that attribute and you end up with

```
BDAY:1604-05-09
```

I'am sorry.

**Comment by samdmarshall** [comment]
Hmmm, would you consider adding support for this specific extension for vcards using 3.0 format? I wouldn't mind switching to 4.0 format so long as that didn't have any negative implications with syncing across iCloud.

**Comment by scheibler** [comment]
Due to the very weak and unspecific vcard standard there are so many private extensions, defined by
Google, Apple and others, that I'am currently unable to work around all that. Simply too much for
such a small project like khard.

As a first step, you could try to create a vcard version 4.0 contact, synchronize it with the iCloud and
test, if Apple supports that:

```
echo -e "First name : John\nLast name : Doe\nBirthday : --02-20" | khard new -a ADDR_BOOK_NAME --vcard-version=4.0
```

If the contact's birthday is shown correctly, then you could convert the contacts in question
and create new ones with vcard version 4.0. See khard's config file, section vcard, option
preferred_version.

But the conversion must be done by hand. Unfortunately that's not trivial. See the comments in the
contacts editor. Some attributes differ in use between 3.0 and 4.0.

**Comment by samdmarshall** [comment]
yeah that is understandable. I'll give the vcard 4.0 stuff a shot and see how it goes, though initially not optimistic since apple's mac software seems to only export to v2.1 and v3 of vcard formats (maybe they support v4, idk).
