### ISSUE TITLE
Add FN (Full Name) of vCard to display configuration

### ISSUE THREAD

**Issue by adamcavendish** [scheibler/khard#171]
Also mentioned in #89 by @madduck , there's a "FN" field in vCard.

Not only same first name and last name people exists in real world, there are also some countries put last name first and first name afterwards, i.e. China, Japan, etc.

As a result, it would be better if 'FN' is configurable in khard. Thx.

**Comment by hydrargyrum** [comment]
Agreed, first name and last name can still be asked by default, for compatibility, and fill FN field based on this, but it's mandatory to allow users to fill/search only FN and not requiring first name/last name.

BTW, this [article about people names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) is a must-read.

**Comment by lucc** [comment]
I would suggest to make the `FN` field editable instead of configurable.  

**What does that mean?**
It will appear in the yaml version of the contact used for editing.  All changes made there are "user intended" and will not be touched by khard.  *Iff* the `FN` is empty (after editing a contact or after creating a contact) khard will fill in some (not configurable) default value. The filling in can be one by the same algorithm we already have.

**Pros over configurable `FN`:**
* I think this is more flexible for the end user 
* it is easier to implement as it does not require yet another config option that has to be handled and documented.

**Cons over configurable `FN`:**
* The user can not change the `FN` field of all contacts at once in a simple way when they decide they want to switch such a scheme.
* If the user prefers any other scheme over the default which is filled in by khard they have to edit it manually for all (also new) contacs.

@hydrargyrum I have read that some time before, it is funny. But actually the vcard already forces us to use *one* special data representation. And luckily `FN` is the only required field in vcards. So we are as flexible as it can possibly be. I also read that link as an argument pro editing `FN`.

**Comment by hydrargyrum** [comment]
> **Pros over configurable `FN`:**
> 
>     * I think this is more flexible for the end user
>     * it is easier to implement as it does not require yet another config option that has to be handled and documented.

Add that it's the only viable field for some countries.

> **Cons over configurable `FN`:**
> 
>     * The user can not change the `FN` field of all contacts at once in a simple way when they decide they want to switch such a scheme.
>     * If the user prefers any other scheme over the default which is filled in by khard they have to edit it manually for all (also new) contacs.

Not necessarily, suppose a vcard has first name "John", last name "Smith", full name "John Smith", and configured scheme is "{first_name} {last_name}". Since full name matches the scheme, it's reasonable to think changing the scheme should also update the full name. If it doesn't match, it's a custom FN, then FN must be kept as is.

When the user changes the scheme, all vcards could be browsed and those matching the previous scheme could be updated.

**Comment by d7415** [comment]
> > **Cons over configurable `FN`:**
> 
> Not necessarily...

Those cons were for a non-configurable scheme

> When the user changes the scheme, all vcards could be browsed and those matching the previous scheme could be updated.

This would be nice, but it's a lot more work for khard (and its developers).

I think this would have to be a separate command too, else khard might be reverting manual changes. And it would need another configuration option to store the old scheme so that it knows what to look for.

Another option for "custom" schemes might be a sledgehammer-type command to overwrite *all* FNs (if they have the required source fields) to match the new scheme.

**Comment by lucc** [comment]
What do you think of #222?

**Comment by lucc** [comment]
closed by #222
