### ISSUE TITLE
API changes break external tools

### ISSUE THREAD

**Issue by serussell** [scheibler/khard#217]
Commit 3cbb4431535dde5f03240c65fd16ab50764a2c1f deleted `get_email_addresses`, which is used by [deoplete-khard](https://github.com/nicoe/deoplete-khard) -- breaking that other package.  I see no mention, warning, or reason for this backwards-incompatible change.  khard has been on 0.x.y versions for three years now, and it breaks the API about once a year.  I'd love to see either API stability, or the adoption of a scheme to allow downstream projects to manage these sorts of changes.

I'm not the hugest advocate of SemVer, but it's vastly superior than having no way of managing backwards-incompatible API changes.  May I suggest adopting [SemVer](https://semver.org/) and releasing khard 1.0.0?  But, really I'll take *anything* at this point.

**Note for Arch users who find this**
```pacman -U /var/cache/pacman/pkg/khard-0.13.0-1-any.pkg.tar.xz``` 
will roll back khard to the previous version with the working API.

**Comment by d7415** [comment]
> Commit [3cbb443](https://github.com/scheibler/khard/commit/3cbb4431535dde5f03240c65fd16ab50764a2c1f) deleted `get_email_addresses`

No, it didn't. I don't doubt your issue, but that commit does not remove that function.

**Comment by serussell** [comment]
@d7415 :man_shrugging: I'm just a humble end user; I don't use git unless I can't avoid it.  I know the method exists in rev `a4ba0e49e407ac03a80a11a26f9e0cd79db4aebd`, and according to the interwebz, `git log -S get_email_addresses carddav_object.py` should have told me which version deleted it.  I also know that version `0.13.0` has the method, and `0.14.0` does not.  I'm sorry I'm not proficient enough with git to bisect it any further than that.

**Comment by lucc** [comment]
Thank you @d7415 for finding the right commit. The fix for @nicoe should be `s/get_email_addresses()/emails/` because the function turned into a property. But that is just a detail.

@serussell I have two bad news for you:
1. In my understanding khard is already using semver, it's just that we did not reach 1.0 yet.  But there is a milestone for that :)
2. khard is a command line application and does not really provide a public API for python programmers. Until recently we did not even have documentation (I will have to clarify the docs that the python api is not public in the future). Ultimately this is python so you can access any object in any module, I know, but then you have to expect things to break :)
(For the command line interface I am trying to make transition with grace periods and warnings and such, see #174/#213 for example.)

On the other hand: If someone wants to request a public python API in order to include khard into some other application I am happy to discuss this in detail.

**Comment by d7415** [comment]
> Thank you @d7415 for finding the right commit. The fix for @nicoe should be `s/get_email_addresses()/emails/` because the function turned into a property. But that is just a detail.

Thanks! Good spot.
