### ISSUE TITLE
Handle ABLABELS on ORG, ADR and friends

### ISSUE THREAD

**Issue by lucc** [scheibler/khard#221]
This is a bug report extracted from #220.

Currently khard crashes if any attribute containing a list (like `ORG`) also has an ABLABEL attached.

**Comment by lucc** [comment]
We can use this vcard for tests:
```vcard
BEGIN:VCARD
VERSION:4.0
UID:51953f58-237e-429a-a271-cb47c026a895
FN:labeled guy
item1.ORG:Test Inc;Some devision
item1.X-ABLabel:Work
ORG:The Company;The devision
END:VCARD
```

**Comment by rbuchberger** [comment]
For anyone looking for a quick and dirty workaround to this issue, you can just strip out the ABLABELS from all your contacts. Start out in the directory with all your vcards in it (probably `.contacts/(something)/`).

To see how many contacts contain an ABLabel and what information is stored in them, run:

`$ sed -n '/ABLABEL/ p' *`

To strip them out of every file, run the following:

`$ sed -i '/ABLABEL/ d' *`

Breakdown of that command for people like me who don't know sed

* `sed` - stream editor
* `-i` - 'in-place', meaning overwrite files
* `'/ABLABEL/ d'` - delete all lines containing ABLABEL
* `*` - act on all files in this directory

If your ABLabels contain useful information you don't want to lose, you can initialize a git repo in this directory, commit before and after making these changes, and revert the second commit whenever this bug is fixed.

**Comment by d7415** [comment]
I did an ugly thing, that **definitely** needs reviewing because I'm sure I'm missing many edge cases. It also has no tests, but I think I'm onto something. It's not a big diff. I'll try to look at it again and PR it tomorrow, at least as a first attempt.

(Short version: I'm passing ABLABEL'd lists to `convert_to_yaml` as a `dict` and handling it there.)
