### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mcmer** [scheibler/khard#299]
the list of changes since 0.17.0 is quite long.
https://github.com/scheibler/khard/compare/v0.17.0...develop

would you care to tag a new release? 
it would help packaging...

marcus

**Comment by lucc** [comment]
I am busy in September, hope to do it in October.

**Comment by Tonus1** [comment]
As my distribution just published a long awaited release, I would be happy to share to the fellow Slackware users a SlackBuild to ease the installation of khard.
A new release of khard would be nice and could shed some light on the project...
I for one use it daily, mainly in my mutt config.

**Comment by lucc** [comment]
Some light in absence of a release:
- I am maintaining khard, but have no admin rights on the repo
- CI is broken because travis changed their terms of use a while ago
- I am waiting on @scheibler to use Github Actions for CI
- I can, have and will make releases via pypi
- currently one test is broken (which went unnoticed because of the missing CI). I want to fix that before making a release (help and PRs welcome)

**Comment by lucc** [comment]
Currently the test suite is broken (not publicly visible as our ci is defunct too, you have to run the tests manually). So with broken tests it does not make much sense to tag a release.

**Comment by lucc** [comment]
It took much longer than expected but 0.18 is now out:

https://github.com/lucc/khard/releases/tag/v0.18.0
https://pypi.org/project/khard/0.18.0/
