### ISSUE TITLE
Search by id to modify a contact

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#33]
I would like to wrap khard so I can use it to edit my contacts in and from Emacs. My idea would be that a first call to khard gives the user the list of his contacts. The user could then pick one of these contacts and a second call to khard would let him modify it. For that, I need to pass something as a parameter to the second khard call. I thought about using the id number in the first column as shown in `khard list`. But `khard modify -s <id>` does not let the user edit the contact with this number. Even worse, khard lists contacts with this number inside their phone number.  What about adding a `-id <id>` parameter to get just 1 contact instead of `-s`?.

**Comment by scheibler** [comment]
I'am no emacs user. But isn't it possible to set emacs as your default text editor in the
khard config file? If so, you could use the modify action as intended. Internally khard creates a
temporary text file and passes it to the given text editor, specified in khard's config file.
Example is vim: /usr/bin/vim /tmp/temp_text_file_name

**Comment by DamienCassou** [comment]
vim and emacs are very different beasts. With vim, the heart of the user workflow is the terminal: the terminal is first started, then vim is started from the terminal, then vim is quit, then another tool is launched from the terminal (e.g., the compiler or khard), then vim is started from the terminal...

With emacs, the user starts emacs, then launches the compiler or khard from emacs, then opens a file in emacs, then opens another tool from emacs... Emacs is the heart of the user workflow.

Yes, khard already launches Emacs when editing a contact. But that's not the Emacs way of doing it. The Emacs way would be to launch an Emacs command that lists the contacts and lets the user pick one to modify it. For this, the only thing I need from khard is a way to ask khard to modify *this* particular contact, not the first element of a search result which may or may not be the one the user wants to modify.

**Comment by DamienCassou** [comment]
Would you accept a patch that adds `--id` to be used as replacement for `--search` when the contact ID is known? What unique identifier would you use?

**Comment by DamienCassou** [comment]
Is `contact.get_full_name()` supposed unique?

**Comment by scheibler** [comment]
Sorry, I still don't get it.

You want to modify an existing contact without the pickup list, which comes up if you produce ambiguous
results. Example: You call khard modify without any search query and more then one contact in
the address book. So you need an unique id to directly modify a contact like for example `khard
modify --id abc`. But then khard nevertheless would open your favorite text editor (emacs) and you
still would not do it the emacs way cause you open emacs, khard and then emacs again. Why would that
be better then the intermediate pick up from a list step if you at the end still open another emacs
within the kard command?

Consider the special case that your search query would produce exactly one result and khard would
open your editor directly and without the pickup list like so: `khard modify -s "john doe"` or if you
have multiple entries with that name `khard modify "john doe google"`. Would that be sufficient?

Beside that, we have to choose a unique identifier which is suitable for entering. The uid is much
to long and the full name is not unique cause it's allowed to have more than one contact with the
same name. At the moment two contacts are equal, if the output of their print_vcard functions is
equal but that's not very helpful in the id case. Technically we also could use the number of the
first table column (called it id) cause the contact table is sorted. But then you must enter the
same khard command again for the second call. Otherwise you would get a different list index.
Therefore I don't like that solution very much.

In the code from the current master branch you can create a new contact from stdin (readme for
details). Maybe I could enhance this so you also could modify from stdin. I could dump the filled
contact template to stdout where you grab it, change what you want and then pipe it to stdin again.
In the last step you also have to choose the correct contact, otherwise you accidentally overwrite
a different one but I think, that's no big problem. What about that?

**Comment by DamienCassou** [comment]
> You want to modify an existing contact without the pickup list, which comes up if you produce ambiguous results. Example: You call khard modify without any search query and more then one contact in the address book. So you need an unique id to directly modify a contact like for example `khard modify --id abc`. But then khard nevertheless would open your favorite text editor (emacs) and you still would not do it the emacs way cause you open emacs, khard and then emacs again. Why would that be better then the intermediate pick up from a list step if you at the end still open another emacs within the kard command?

Emacs can run as a daemon which means that the `EDITOR` environment variable can start an Emacs client instead of a full-fledged Emacs. Then, the [`with-editor` Emacs package](http://magit.vc/manual/with-editor/) lets Emacs start external processes by binding `EDITOR` to the current Emacs server. This way, you can use external command requiring `EDITOR` without quitting Emacs. This is what is used by `magit` to edit git commit messages.

> Consider the special case that your search query would produce exactly one result and khard would open your editor directly and without the pickup list like so: `khard modify -s "john doe"` or if you have multiple entries with that name `khard modify "john doe google"`. Would that be sufficient?

I guess so, I just need a unique identifier.

> Beside that, we have to choose a unique identifier which is suitable for entering. The uid is much too long

We could use any unique prefix of the uid, just like git does with commit hashes.

> In the code from the current master branch you can create a new contact from stdin (readme for details). Maybe I could enhance this so you also could modify from stdin. I could dump the filled contact template to stdout where you grab it, change what you want and then pipe it to stdin again. In the last step you also have to choose the correct contact, otherwise you accidentally overwrite a different one but I think, that's no big problem. What about that?

That would be the best solution, much better than what I'm currently trying to achieve with `with-editor`. How do you plan to let the user "choose the correct contact"?

**Comment by DamienCassou** [comment]
I've just found https://github.com/flexibeast/org-vcard which might help me edit vcf files within Emacs. If this works, it means I won't need your template. I will just need a way to find the vcf file I want to modify from my vdirsyncer repository. I can use khard for that or I can directly manipulate the vdirsyncer repository.

**Comment by scheibler** [comment]
I've uploaded a new khard version with the following new features:
- use -u uid to select a contact (first n chars of the uid string, until it's unique)
- Create and modify contacts from stdin or template
Please have a look into the readme file for further information and tell me, if that's suitable for you.

**Comment by DamienCassou** [comment]
Thanks @scheibler for this. As I said in the previous comment, I'm exploring a different and more direct path right now.
