### ISSUE TITLE
Bug: additional info from VCF's N Type are lost upon modify

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#38]
Type N holds Family Name, Given Name, Additional Names, Honorific Prefixes and Honorific Suffixes (see 3.1.2. of RFC2426 http://www.ietf.org/rfc/rfc2426.txt).

**khard** only regards the first two of those, causing deletion of the latter upon save.

**khard** should only write to fields it actually also read in, leaving the rest untouched.

**Comment by scheibler** [comment]
Fixed. Thank you.

**Comment by GSI** [comment]
Hm khard still is quite destructive. I issued `khard modify` on my test VCF, saved and closed immediately. Then I did a diff between the original and the newly saved VCF.

The following things happened:

* The original file had two `TEL;TYPE=cell:` lines. One of them vanished upon saving.
* The original file had two `TEL;TYPE=work:` lines. One of them vanished upon saving.
* The original file had two `ADR;TYPE=home:` lines. One of them vanished upon saving.
* The original file had one `TEL;TYPE=x-voice:` line. It was converted to a `itemtel1.TEL:` line and another line stating only `itemtel1.X-ABLABEL:x-voice` was added.
* The original file had a line `ADR;TYPE=home:;door;street;city;city;zip;country`. The `door` part was lost. *(Note my previous comment above in order to conceptually avoid such issues in general: "khard should only write to fields it actually also read in, leaving the rest untouched.")*

Note that the original file was created on Android. In case duplicates are forbidden by RFC (are they?), I'd still expect any software to gracefully handle such errors.

**Comment by scheibler** [comment]
* The original file had two `TEL;TYPE=cell:` lines. One of them vanished upon saving.
* The original file had two `TEL;TYPE=work:` lines. One of them vanished upon saving.
* The original file had two `ADR;TYPE=home:` lines. One of them vanished upon saving.

Oh, I missed that test case. That's an issue of yaml respectively pythons dictionary type. Two keys
with the same name are not possible so the first one is overwritten by the second.  I didn't find
information about duplicate type values in the vcard definition but I guess, that's legal.

I have to think about a solution. For the phone and email addresses this could easily be fixed with
comma separated values but for post addresses, it's more difficult.

* The original file had one `TEL;TYPE=x-voice:` line. It was converted to a `itemtel1.TEL:` line and another line stating only `itemtel1.X-ABLABEL:x-voice` was added.

This x-... values are a custom enhancement of the vcard standard by Android
(https://tools.ietf.org/html/rfc6350#section-6.10). Every type, which is not one of the listed
standard ones is considered as a custom one. I've copied the custom type handling from my Android
version (4.4) and I doubt, that these work with other vcard client software but I found them useful
and cause I use an Android device too, I decided to implement that. To make that clear, the
description for the phone numbers in the modify document tells the user, that custom labels may not
be supported within all vcard clients.

Problem is, that Android obviously changed it's own custom label behavior and so it's almost
impossible to achieve a sane implementation. For me, that itemtelx... tags work and the custom
labels are shown in Android's contact App. Your type value otherwise doesn't work for my Phone. I
could leave already existing custom types untouched but how to add new ones? With your or with my
variant? Or leave them out completely and force the user to only use standard types?

* The original file had a line `ADR;TYPE=home:;door;street;city;city;zip;country`. The `door` part was lost.

The vcard standard recommends, that postbox and door should be blank for optimal interoperability
(https://tools.ietf.org/html/rfc6350#section-6.3.1). But I will support that first two fields
nonetheless.

* (Note my previous comment above in order to conceptually avoid such issues in general: "khard should only write to fields it actually also read in, leaving the rest untouched.")*

Actually that's done right now. Your first issue is a khard bug, the second one relates to an
awkward incompatibility problem and the last one is also more or less a khard bug.

Khard only removes and adds supported attributes like tel or adr but for example leaves the photo or
geo attribute untouched. But it's right, that all supported attributes are deleted and re-added if
you only change one of them. So if you change for example the contact's birthday, also the
problematic phone attribute is rewritten and possibly corrupted. But if I would compare the new
input to the old vcard file and only rewrite the parts, which the user really changed, I only would
delay the problem. Yes, for the birthday example that would work and your file would not be damaged
but if you want to add a phone number or change an existing one, you're still involved in the custom
type problem. So it's the question, if the code changes would be worth it. I think, we need a
solution for the custom types instead.

**Comment by scheibler** [comment]
>* The original file had two `TEL;TYPE=cell:` lines. One of them vanished upon saving.
>* The original file had two `TEL;TYPE=work:` lines. One of them vanished upon saving.
>* The original file had two `ADR;TYPE=home:` lines. One of them vanished upon saving.

This should work now.

>* The original file had one `TEL;TYPE=x-voice:` line. It was converted to a `itemtel1.TEL:` line and another line stating only `itemtel1.X-ABLABEL:x-voice` was added.

As I already wrote, this is difficult to fix. Please try out the x-ablabel solution, created by
khard, on your Android phone. Maybe it's also working.

>* The original file had a line `ADR;TYPE=home:;door;street;city;city;zip;country`. The `door` part was lost.

Fixed.

If you still encounter bugs, please send me your example vcard file. That would make debugging a lot easier.

**Comment by GSI** [comment]
Thanks for the updates.

I think I fail to understand the **x-voice** issue: Why not just write it as `TEL;TYPE=x-voice:XXXXXXX` to the vcf? Illegal?

**Comment by scheibler** [comment]
In the latest commit I use both: a custom x-ablabel to support the contacts app of my Android
version and the type=x-... for you. That's working for me. The custom string in the type param is
ignored by my Android device. Please test, if you also can live with that.

Unfortunately your x-voice is a special case: On input, khard strips the "x-" prefix from the custom
type for a better usability. After editing is complete, every type value is compared to the standard
type list for the particular attribute to decide, if it's a standard or custom one. If it's the
latter, create a x-ablabel and add it to the "type" param, prefixed with "X-". But if I strip your
"x-voice", I get voice, which is the default value for phone numbers, if you don't specify a type at
all. So it will be re-added as "TYPE=VOICE" instead of "TYPE=X-VOICE" and without a grouped
x-ablabel. Therefore I don't know, why they use "X-Voice" at all if "voice" already exists. But if I
don't strip the "x-" prefix, it's also added to the grouped x-ablabel and consequently shown in my
Android contacts app and I don't like that either. So the current solution is the best compromise, I
came around with.

**Comment by GSI** [comment]
The VCF in question is probably the oldest I have. It's "myself", being migrated from one phone to the next probably since Nokia 9110 days.

I just checked my whole contact database and it turns out it's the only one with an `x-voice` type. Given it actually is a normal phone number, I suppose there's no reason not to simply convert it to `voice`.

Personally, I'd skip the stripping of the `x-` for editing: It's not a lot of extra typing, the list of standard-fields is short (14 items?) and at it would make the user aware that he's adding/editing a non-standard field.

I'd even vote for listing all standard fields in the yaml (instead of naming them in the comments).

**Comment by scheibler** [comment]
>I'd even vote for listing all standard fields in the yaml (instead of naming them in the comments).

In my opinion, it's too much overhead. Who still wants to add a modem or isdn number? And you also
have to consider, that combinations like "fax, home" or "pager, work" are possible too.

**Comment by GSI** [comment]
Got it. You're right.
