### ISSUE TITLE
khard should not save unless I do

### ISSUE THREAD

**Issue by GSI** [scheibler/khard#42]
My editor is **vim**. When I `khard modify` a contact and leave the editor without changing anything (`:q`), then khard still rewrites the contact.

That should be avoided as it's unexpected behaviour and allows to data corruption to sneak in.

**Comment by scheibler** [comment]
Yes, that means, that there is still a bug in the parsing method.

Two vcards are equal, if the output of their print_vcard method is equal (simple string comparison).
First I would use the UID but unfortunately that attribute is not mandatory.

If khard outputs "modification successful" instead of "nothing changed", there has to exist a
difference in the detailed vcard output string. Please could you send me your example vcard file so
that I can debug that?

**Comment by GSI** [comment]
How about using something safer instead? The file's mtime maybe?

**Comment by scheibler** [comment]
Modification date of temp file seems to work. If you at least wait 0.3 seconds before you close the
text editor, it should be all right.

**Comment by scheibler** [comment]
Forget about the 0.3 seconds. Now the modification date before editing is compared to the
modification date afterwards. Much less error-prone.

**Comment by GSI** [comment]
Cool!
