### ISSUE TITLE
Add flag to display results in computer-readable format

### ISSUE THREAD

**Issue by teto** [scheibler/khard#48]
I've started writing a YouCompleteMe completer for khard. 
I don't work with the cache yet, I just run requests with subprocess.check_output("khard -s %s" ).
I've stopped there because it would be nice if the output could be with the JSON format so that I can use the json library in python to process the resultsL.

**Comment by scheibler** [comment]
You may find the template, that's used to create and modify contacts, suitable for your needs. The
template is yaml formatted - also a machine readable data structure and related to json.  Please
have a look into the process_user_input function in the file khard/carddav_object.py to learn, how
I've used it.

You can print the template for a selected contact to stdout like:

```
khard export [-s search] [-u uid]
```

Or export to file:

```
khard export -t template.yaml [-s search] [-u uid]
```

Was this helpful to you or do you need anything else?

**Comment by teto** [comment]
if I run "khard export -s to", it will first display a human readable list asking for a UID and only then display a YAML version. 
When using YouCompleteMe, I don't know the UID yet (somehow that's what the user is searching).

**Comment by scheibler** [comment]
Khard shows the contact list, if your search query is ambiguous. Otherwise it will select the
contact without user interaction.

What exactly do you need for your completion function? For example I could add a new option for the
list action, which presents the contact list in machine readable form - let's say tab-separated,
similar to the output of the email or phone action. Yaml would be possible too. Or should khard
output the whole address book in machine readable form with a single export command? If you want to
complete addresses and phone numbers in a vim document, the ladder seems more reasonable to me cause
you only would need to query khard once to get all address book data.

And finally: Although many contacts contain a valid uid, beware, that the uid is not mandatory for
vcards. So don't rely on that too much.

**Comment by teto** [comment]
I am just trying to autocomplete email adresses, like if I start typing
"pat", then a list of all contacts matching a "pat" request should be
returned.
- One possibility could be to let YouCompleteMe cache everything but this
is too advanced for me.
- the second is to relaunch queries when people type more characters.
I would like to check if "pat" is part of the name/surname/email. For
instance I type "patrick" and then I select the result "Patrick Schmidt"
and vim replaces what I typed by his email "pat.schmidt@DeutschTelekom.de"

My wished behavior would be for now :
```khard export --json/--csv -s "pat"```
and it returns name,surname,email. I could parse yaml as well for tests but
that adds a dependancy and might be slow.

I thought the UID was generated by khard ok interesting ^^


2016-02-10 14:32 GMT+01:00 Eric Scheibler <notifications@github.com>:

**Comment by scheibler** [comment]
If you only want to query email addresses or phone numbers, you may use the "email" or "phone" action:

- Email line format: email_address<tab>contact_name<tab>email_type
- Phone line format: phone_number<tab>contact_name<tab>phone_type

Make sure, that you skip the first line of the email output (mutt requires that first line,
otherwise the address querying fails).

I suggest, that you call `khard email` or `khard phone` without further arguments, to load all email
addresses or phone numbers at once. But if this produces performance issues, you also could search
for a specific name instead.

**Comment by teto** [comment]
That should be good enough for my tests thanks. I will reopen if I change my mind.
