### ISSUE TITLE
Reading from stdin

### ISSUE THREAD

**Issue by DamienCassou** [scheibler/khard#61]
In release 0.8.1, there is this code:

```python
    if args.action in ["add-email", "new", "modify"]:
        if args.template_file:
            with open(args.template_file, "r") as f:
                input_from_stdin_or_file = f.read()
        elif not sys.stdin.isatty():
            input_from_stdin_or_file = sys.stdin.read()
            sys.stdin = open('/dev/tty')
```

I don't understand the last 3 lines. If `stdin` is not a tty, you read from it and you change `stdin`. That doesn't work for me:

```
Traceback (most recent call last):
  File "/nix/store/x3prggi9nblisvx3c4nszh4az744dqxw-khard-0.8.1/bin/.khard-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/x3prggi9nblisvx3c4nszh4az744dqxw-khard-0.8.1/lib/python2.7/site-packages/khard/khard.py", line 461, in main
    sys.stdin = open('/dev/tty')
IOError: [Errno 6] No such device or address: '/dev/tty'
```

**Comment by scheibler** [comment]
The three lines mean: If there is something in stdin, save contents of stdin into string variable
and reopen /dev/tty. The last command is necessary, cause otherwise you can't react to eventually
occuring dialogs, which require user interaction (for example selecting a contact from the contact
table). So reopen /dev/tty means, that the program awaits input from the keyboard instead of stdin
from now. I don't know, why your system doesn't provide /dev/tty or why opening fails. It should
exist on all unix systems which provide a controlling terminal (but I'am no expert in that).

In the meantime I will wrap that command in a try-catch-block. This doesn't solve your issue
completely but at least you can try to input data from stdin, if you make sure, that you don't
produce situations, where user input is necessary.
